version: "3.8"
services:
  lbg:
    build: .
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    networks: lbg-python-net
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    networks: lbg-python-net
networks:
  lbg-python-net:
